### ISSUE TITLE
Não consigo pesquisar nada!

### ISSUE THREAD

**Issue by drag0nst0ne** [uilton-oliveira/LegendasTvDownloader#10]
Toda vez que vou pesquisar uma serie, seja manual ou clicando no video. Esse erro aparece
![image](https://user-images.githubusercontent.com/50338430/128392907-eea8f3f5-7396-4917-8353-458a148f7525.png)

**Comment by uilton-oliveira** [comment]
Parece que deu algum problema no build, vou dar uma olhada aqui..

**Comment by uilton-oliveira** [comment]
@drag0nst0ne resolvido e lançado uma nova versão: https://github.com/uilton-oliveira/LegendasTvDownloader/releases/tag/v2021-08-12-897895ae
